### ISSUE TITLE
Where to start

### ISSUE THREAD

**Issue by Montanadude** [jagadish-pattanaik/aide-chatbot#1]
I have an Inmoov head and was wondering if you can expand a bit more for using the aide-chatbot code?  I have also sent you a message on discord.  I'd like to give the code a try, but not sure how to integrate it.  Thanks!

**Comment by jagadish-pattanaik** [comment]
will send you full details on github properly

**Comment by jagadish-pattanaik** [comment]
so in your inmoov folder where all aiml files are there you can add there all these aiml files and the restart your inmoov to load all aiml data into it
